### ISSUE TITLE
Can generate content by JSON files

### ISSUE THREAD

**Issue by Lowell130** [pengutronix/flamingo#16]
Can generate content by JSON files?

**Comment by fscherf** [comment]
hi @Lowell130,

what do you mean? Do you want to use JSON for your meta data, or do you want to add complete content files containing JSON?

In both cases you would need to add a new flamingo parser. I currently write documentation on how to do it, and could provide you a snippet to start with

**Comment by Lowell130** [comment]
i just want generate static HTML pages by JSON data, it's possible?

**Comment by Lowell130** [comment]
> hi @Lowell130,
> 
> what do you mean? Do you want to use JSON for your meta data, or do you want to add complete content files containing JSON?
> 
> In both cases you would need to add a new flamingo parser. I currently write documentation on how to do it, and could provide you a snippet to start with

i just want generate static HTML pages by JSON data, it's possible?

**Comment by fscherf** [comment]
Flamingo has no native support for JSON files. You would need to write a plugin with ~10 lines of code i think. But then you can use JSON files. So yes and no.

**Comment by fscherf** [comment]
@Lowell130 does this answer your question?

**Comment by Lowell130** [comment]
> @Lowell130 does this answer your question?

i don't know how do that, can you help me?

**Comment by fscherf** [comment]
Ah ok! If i understand you correctly, you want to create one HTML page as singe page application and store all contents as JSON files to load them from the HTML page using JS?

In this case you can do something like this:

```python

class SinglePageApplicationPlugin:
    def contents_parsed(self, context):
        data = []

        for content in context.contents:
            data.append({
                'title': content['content_title'],
                'body': content['content_body'],
            })

        json.dumps(data)
```

**Comment by Lowell130** [comment]
> Ah ok! If i understand you correctly, you want to create one HTML page as singe page application and store all contents as JSON files to load them from the HTML page using JS?
> 
> In this case you can do something like this:
> 
> ```python
> class SinglePageApplicationPlugin:
>     def contents_parsed(self, context):
>         data = []
> 
>         for content in context.contents:
>             data.append({
>                 'title': content['content_title'],
>                 'body': content['content_body'],
>             })
> 
>         json.dumps(data)
> ```

not exactly i just want generate html pages for each item stored in my json. In my json i have lots of items with their key value infos, there e sample of json file: https://easyupload.io/nqhnc2

**Comment by fscherf** [comment]
ah ok! Then you could should write a [parser](https://flamingo-web.org/cookbook/how_to_write_a_parser.html)

```python
import json

from flamingo.core.parser import ContentParser


class JSONParser(ContentParser):
    FILE_EXTENSIONS = ['json']

    def parse(self, file_content, content):
        for entry in json.loads(file_content):
            content['content_title'] = entry['title']
            content['content_body'] = entry['body']


class JSON:
    def parser_setup(self, context):
        context.parser.add_parser(JSONParser(context))
```

**Comment by Lowell130** [comment]
> ah ok! Then you could should write a [parser](https://flamingo-web.org/cookbook/how_to_write_a_parser.html)
> 
> ```python
> import json
> 
> from flamingo.core.parser import ContentParser
> 
> 
> class JSONParser(ContentParser):
>     FILE_EXTENSIONS = ['json']
> 
>     def parse(self, file_content, content):
>         for entry in json.loads(file_content):
>             content['content_title'] = entry['title']
>             content['content_body'] = entry['body']
> 
> 
> class JSON:
>     def parser_setup(self, context):
>         context.parser.add_parser(JSONParser(context))
> ```

wow please give me time to check your great solution

**Comment by fscherf** [comment]
Hi @Lowell130,

This issue is still open. Did my example solve your problem?
