### ISSUE TITLE
Local environment on Windows

### ISSUE THREAD

**Issue by Lowell130** [pengutronix/flamingo#19]
Hello how i can install locally with windows flamingo?

**Comment by fscherf** [comment]
Flamingo is intended to be installed via `pip` to bootstrap a flamingo project using `flamingo init`. This is not tested on windows and i have no idea if it works or not. It would be great if you could share your experiences if try to do so.

I have no clue about python on windows but i'll try to help if you run into issues.

**Comment by fscherf** [comment]
Hi @Lowell130,

This issue is still open. I don't plan to include or even test windows compatibility, because i don't have access to a windows machine. Do you want to contribute code or documentation?
