### ISSUE TITLE
Problems with images in markdown

### ISSUE THREAD

**Issue by AlarithUhde** [pengutronix/flamingo#21]
Hi!

I'm trying to include an image in a blog post using markdown. This is my content file:

```yaml
title: Homepage
author: alice
published: 2020-05-01
modified: 2020-05-02
description: A test description
tags: [ドイツ, アメリカ]
output: index.html
template: blog-post.html
```
```markdown
# Home World

Welcome everybody else!

<picture>
  <source srcset="media/P4171125-768x576.webp"/>
  <img alt="Beatles" src="media/P4171125-768x576.jpg" style="width:auto;"/>
</picture>

<img alt="Alt text" src="media/P4171125-768x576.jpg" title="Optional title"/></p>

![alt text](media/P4171125-768x576.jpg "title")
```

After making the html file, the image sources are cut out (except for the alternative source in the picture tag):

```html
  <h1>Home World</h1>
  
<p>Welcome everybody else!</p>
<p><picture>
<source srcset="media/P4171125-768x576.webp"/>
<img alt="Beatles" src style="width:auto;"/>
</picture></p>
<p><img alt="Alt text" src title="Optional title"/></p>
<p><img alt="alt text" src title="title"/></p>

      </div>
    </main>
    <footer class="border-top">
    </footer>
    <script src="/static/jquery/jquery-3.4.1.min.js"></script>
    <script src="/static/bootstrap-4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>
```

the template file looks like this:
```jinja
{% extends "base.html" %}

{% block structured_data %}
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "BlogPosting",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "{{ context.settings.PROJECT_URL }}{{ content.url }}"
      },
      "headline": "{{ content.content_title }}",
      "image": [
        "https://example.com/photos/1x1/photo.jpg",
        "https://example.com/photos/4x3/photo.jpg",
        "https://example.com/photos/16x9/photo.jpg"
       ],
      "datePublished": "{{ content.published }}",
      "dateModified": "{{ content.modified }}",
      "author": {
        "@type": "Person",
        "name": "{{ content.author }}"
      },
       "publisher": {
        "@type": "Organization",
        "name": "{{ context.settings.PROJECT_NAME }}",
        "logo": {
          "@type": "ImageObject",
          "url": "https://google.com/logo.jpg"
        }
      },
      "description": "{{ content.description }}"
    }
    </script>

{% endblock %}

{% block title %}{{ context.settings.PROJECT_NAME }} - {% if content.title %}{{ content.title }}{% else %}{{ content.content_title }}{% endif %}{% endblock %}

{% block content %}
  <h1>{{ content.content_title }}</h1>
  {{ content.content_body }}
{% endblock %}


```

As far as I understand it, I have to include the images in the article in order for them to appear in the media content set. But I'm a bit stuck because when I include them, they are cut out. My next solution would be to include them, have them cut out, and then reinclude them with jinja, but that seemed a bit too complicated for a simple picture, so I don't know how to proceed.

In contrast, rst seems to work fine. This:

```rst
Home World
==========

Welcome everybody else!


.. image:: media/P4171125-768x576.webp

.. image:: media/P7121696-768x576.jpg
    :alt: My bar image
    :title: My bar image

    This is the caption of my bar image.
```

produces meaningful html (I deleted some whitespace):

```html
  <h1>Home World</h1>
  <p>Welcome everybody else!</p>
<img src="/media/P4171125-768x576.webp"
  style="
  ">
<div class="image"
   style="
   "><img src="/media/P7121696-768x576.jpg
     alt="My bar image"
     title="My bar image"
  style="
  ">
<div class="caption"
    style="
      "><p>This is the caption of my bar image.</p>
</div>
  </div>
      </div>
    </main>
    <footer class="border-top">
    </footer>
    <script src="/static/jquery/jquery-3.4.1.min.js"></script>
    <script src="/static/bootstrap-4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>
```

I'm a bit stuck with this issue and didn't find out how to solve it through the documentation so far. I also checked the python-markdown documentation for a possible plugin, but didn't find any (and image handling is not listed among the differences to regular markdown). If the sources are supposed to be cut out, the fact that the "srcset" isn't seems like a bug to me. Any ideas or easy solutions to this? Thanks a lot!

**Comment by fscherf** [comment]
Hi @AlarithUhde,

I am very sorry! You did everything right and ran in bug in the flamingo core. Thanks for debugging and providing so much information, that made it very easy to find the bug.

The problem is very simple: When the media content api was new, it had different meta data keys than the normal content objects. Content objects used ``content['url']`` and media contents used ``media_content['link']``.  When i fixed this i evidently missed some parts of the old code.

I added a test that reproduces your problem, added a fix and released a bugfix release. After an update, your blog post should work just fine.

Thanks for contributing! :)

**Comment by AlarithUhde** [comment]
I upgraded flamingo to 1.2.2 and that fixed the problem! Thanks a lot again!
